#%RAML 0.8
title: microservice-template
version: 0.1
mediaType: application/json

/ping:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "ok"
              }

/health:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "ok"
              }

/basic:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "method": "get"
              }
