apiVersion: v1
kind: Service
metadata:
  name: microservice-template
  namespace: exchange
  labels:
    name: microservice-template
    k8s-app: microservice-template
spec:
{{- if .Values.service.external }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end}}
  ports:
    - name: microservice-template
      port: {{.Values.service.port}}
      targetPort: 3001
  selector:
    app: microservice-template
    name: microservice-template
